numpy is faster than lists...like way faster
numpy - int32/ int16/ int8 - 4bytes   - contigous memory - less time to traverse
- SIMD vector processing unit(single instruction multiple data)
- effective cache utilization

lists - built in 4 types - depends and obviously more memory than a numpy array
- scattered memory - not in an order - so more time to traverse

difference
numpy - do stuff faster and effecient..easy - math

list - not better than numpy, lets see in the practical

Applications of numpy
- math(matlab)
- plotting(matplotlin)
backend - pandas
Machine learning (tensor and stuff like that) - dont know right now

In [2]:
import numpy as np
import random

# The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dinension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get shape
print(a)
print(a.shape) #vector
print(b)
print(b.shape)
# now it should make sense

[1 2 3]
(3,)
[[9. 8. 7.]
 [6. 5. 4.]]
(2, 3)


In [7]:
# Get type and the size
print(a.dtype,
b.dtype)

int64 float64


In [8]:
# Creating the array and specifying the dtype and size
a = np.array([1,2,3], dtype = 'int16')
print(a.dtype)

int16


In [9]:
# get size
a.itemsize # this will print the number of bytes

2

In [10]:
# suppose i re assign the values
a = np.array([1,2,3], dtype = 'int32')
print(a.itemsize) # now it will show the 4 bytes - 32/8 = 4 bytes

4


In [11]:
# get total size
a.size
# the total number of elements inside it

3

In [12]:
# get total size
a.size * a.itemsize
# total storage taken by the array

12

In [13]:
# get total size
a.nbytes
# same thing as above

12

In [14]:
# b is float
print(b)
# 6 items in 2 lists and they are in float64 format

[[9. 8. 7.]
 [6. 5. 4.]]


In [15]:
# reassigning the dtype to b
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]], dtype=np.float32)
# floats are bigger than integers
# use np.float32

In [16]:
b.nbytes

24

In [17]:
b.size * b.itemsize

24

#**Accessing/Changing specific elements, rows, columns, etc**

In [18]:
# Creating a 2D array
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# this should be a 2/7 array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
print(a.shape)

(2, 7)


In [20]:
# Get a specific element [r, c]
# trying to get 13
a[1,5] # numbers through indexing

13

In [21]:
# using the -ve notation similar to lists
print(
    a[1,-2]
)

13


In [22]:
# get a specific row
print(
    a[0]
)

[1 2 3 4 5 6 7]


In [23]:
# getting everything in the row
print(
    a[0, :]
)

[1 2 3 4 5 6 7]


In [24]:
# get a specific column - 3, 10
print(
    a[:,2]
)
# everything from the second column

[ 3 10]


In [25]:
# getting little more fancy [startindex : endindex : stepsize]
print(a)
# getting num from 2 and 6

a[0,1:6]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 3, 4, 5, 6])

In [26]:
# getting the same output as the a[0,1:6]
print(
    a[0,1:-1]
)

[2 3 4 5 6]


In [27]:
# now using the stepsize and getting the even numbers
print(a)
print(
    a[0,1:6:2]
) # 2,4,6 will be outputtes

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[2 4 6]


In [28]:
# changing the values
# from 13 to 20

print(a)

(a[1,-2]) = 20

print("now it is changed")
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
now it is changed
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
# changing for series of numbers like for an entire column
# that 3,10 column

print(a)
a[:,2] = 5

# now the entire row will get the 5 as its value
print("after changing")
print(a)
print("changing it to be two different numbers")
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
after changing
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
changing it to be two different numbers
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# **3D example**

In [30]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# get a specific element (work outside in)
# getting 4 from b
b[0,1,1]

4

In [32]:
# getting [3,4],[7,8]

b[:,1,:]
# everything from the first index and the 2nd one and everythin grom the 2nd row

# just play around

array([[3, 4],
       [7, 8]])

In [33]:
# replacing the subsequent sets of same dimension
b[:,1,:] = [[9,9,],[8,8]]
print(b)

# challenge at the end of the video

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# **Initializing Different Types of Arrays**

In [34]:
# All 0's matrix

# builtin function
np.zeros(5) # - gives me a vector of length 5

# going 2d
np.zeros((2,3)) # 2*3 matrix

# going 3d
np.zeros((2,3,3))

# always use a double parenthesis

# going 4d
np.zeros((2,3,3,2))

# will print all zeros
# yeah it gets more craazy

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [35]:
import numpy as np
# All one's matrix 1's
np.ones((2,3))

# yeah similar to the zeros


# All ones but int32
one = np.ones((4,2,2),dtype='int8')

print(one.nbytes) # will be 1 byte
print(one)

16
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [36]:
# using other number for the creating an array with a particular number
np.full((2,2),99, dtype='float32')

# here we just stated that we need a 2*2 matrix with full of 99 in it

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [37]:
# Any other number (full_like)
# reuse 'a' array
print(a)

a4 = np.full_like(a,4)

print(a4)

# a4 has the same shape/dimension as the 2*7
print(a.shape)
print(a4.shape)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
(2, 7)
(2, 7)


In [38]:
# Initialize a array with random decimal number
np.random.rand(4,2,3)
# instead of passing a tuple(double parenthesis) we can pass directly

# it will create a random float in the dimensions

array([[[0.1490461 , 0.49210742, 0.49858267],
        [0.8990654 , 0.10464762, 0.90878862]],

       [[0.02387346, 0.87564604, 0.84691479],
        [0.86418859, 0.11975913, 0.22538717]],

       [[0.38287925, 0.49716871, 0.36977521],
        [0.21499232, 0.99826682, 0.06962754]],

       [[0.11423203, 0.28368619, 0.40011011],
        [0.34746004, 0.08033629, 0.41287731]]])

In [39]:
# passing a previously made shape
np.random.random_sample(a.shape)
print(np.random.random_sample(a.shape).shape)
# same shape as the a -- 2*7

(2, 7)


In [40]:
# Random integer values
np.random.randint(7, size = (3,3))
# generates stuff between 1 and 7 in a 3*3 matrix
np.random.randint(4,7, size = (3,3))
# generates stuff between4 and 7 in a 3*3 matrix
np.random.randint(-4,7, size = (3,3))

array([[-2, -2,  3],
       [ 5, -2,  3],
       [ 6,  6,  1]])

In [41]:
# identity matrix - 1 parameter - square
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# repeat arrays a few times
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)
# 2d array
ar2 = np.array([[1,2,3]])
r2 = np.repeat(ar2,3,axis = 0)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
# challenge
ch = np.zeros((5,5))
print(f"{ch}\n\n")
ch[0] = [1]
ch[4] = [1]
ch[:,0] = [1]
ch[:,-1] = 1
ch[2,2] = 9
print(ch)

# this is my solution

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
# keith solution
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

# replace the middle part of the ones matrix
output[1:4,1:4] = z   # instead of output you can also use -1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays

In [45]:
a = np.array([1,2,3])
# a is just a normal array

# now we want to make 'b' a direct copy of 'a'
b = a
print(a)
print(b)

# now changing b

b[0] = 100
print(b)
print(a)

# now even 'a' is changed when we changed values of 'b'

# because when we set b = a the varaible is pointing at the same location

# so instead of it we are using copy() function

print("\n\nUsing the copy function")
a = np.array([1,2,3])
print(a)
b = a.copy()
print(b)
print("changing the value of 'b'")
b[0] = 100
print(a)
print(b)
# now the value of a is not changed since the a new array is created and
# it is pointing to a different location

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


Using the copy function
[1 2 3]
[1 2 3]
changing the value of 'b'
[1 2 3]
[100   2   3]


# **Mathematics**

In [46]:
# "Element" wise addition subtraction....math operations
a = np.array([1,2,3,4])
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [47]:
b = np.array([1,0,1,0])
print(a**b)
print(a*b)
print(a-b)
print(a+b)
# element wise addition...can be done any math ops

[1 1 3 1]
[1 0 3 0]
[0 2 2 4]
[2 2 4 4]


In [48]:
# tirgnomateric operations

# take the sin of all values
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


# **Linear Algebra**

In [49]:
# Basic and functions on elements - like matlab kinda LA

# Not doing element wise

a = np.full((2,3),1) # 2*3 matrix of all ones
print(a)

b = np.full((3,2),2)
print(b)

# yo know basics math operation  like the matrix multiplication
# but still the a*b is not gonna work because they are of different sizes

# so now we need to use the matmul()

np.matmul(a,b) # regular math - dimension compatibility

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [50]:
# find the determinent of the matrix

# determinent of the identity matrix is one(always)
c = np.identity(3)
print(c)
det_c = np.linalg.det(c)
print(det_c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [51]:
# eigen value, inverse of a matrix
# just go to the documentation or the chatgpt


# **Statistics**


In [52]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

# min of it
print(np.min(stats))
# max of it
print(np.max(stats))

# doing it on a row basis - axis = 1
print(np.min(stats, axis = 1)) # shows the minimm in column wise
print(np.min(stats, axis = 0)) # shows the minimum in row wise

[[1 2 3]
 [4 5 6]]
1
6
[1 4]
[1 2 3]


In [53]:
# max of it
print(np.max(stats))

print(np.max(stats, axis = 0))
print(np.max(stats, axis = 1))

6
[4 5 6]
[3 6]


In [54]:
# summing stats
np.sum(stats)

np.sum(stats, axis = 0)
np.sum(stats, axis = 1)

# when axis = 0 -- column
# when axis = 1 -- rows

array([ 6, 15])

# **Reorganizning Arrays**

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

# changing its shape
after = before.reshape((8,1))

print(after)

after2 = before.reshape(4,2)

print(after2)

after3 = before.reshape(2,2,2)
print(after3)
print(after3.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


You can just re organize it as long as it has the same number of elements
like  
2 * 2 * 2 = 8                
2 * 4 = 8                  
4 * 2 = 8             
8 * 1 = 8              
like that

In [56]:
# Vertically stacking vectors or matrices - dimension are important
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
# now this will be a matrix and just stacks them in a matrix manner

# doing it again and again(repetetive)
np.vstack([v1,v2,v1,v2])

# or i need 3 copies of v2 below 1 copy of v1
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [57]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

print(h1)
print(h2)
print(np.hstack([h1,h2]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# **Miscellaneous**

**Load Data from File**

In [73]:
from google.colab import drive
drive.mount('/content/drive')


fp = "/content/drive/My Drive/Colab Notebooks/data.txt"

# delimiter - seperator
filedata = np.genfromtxt(fp, delimiter = ',')
print(filedata)
# automatically casts it into float
filedata = filedata.astype('int32')
print(filedata)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[ 11. 178.  44.  41.  52.  46.  84.   5.  63.  98.  63.]
 [  3.   2.   5.   6.  89.  56.  22.  33.  54.  65.  89.]]
[[ 11. 178.  44.  41.  52.  46.  84.   5.  63.  98.  63.]
 [  3.   2.   5.   6.  89.  56.  22.  33.  54.  65.  89.]]


**Boolean masking and advanced indexing**

In [77]:
# Advanced indexing

print(filedata > 50)  # boolean based on the value

print(filedata[filedata > 50]) # will output the values where the value is greater than 50

[[False  True False False  True False  True False  True  True  True]
 [False False False False  True  True False False  True  True  True]]
[178.  52.  84.  63.  98.  63.  89.  56.  54.  65.  89.]


In [84]:
## You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
# 0,2,last spots

lst = [1,2,-1]

a[lst] == a[[1,2,-1]]
print(a[0:3:2]) # -- that start:end:step indexing

[1 3]


In [99]:
# any value is greater than 50 in filedata column wise
print(filedata)

print(np.any(filedata > 50, axis = 0))

# checking row wise if there is any value in the row that is more than 50
print(filedata)
print(np.any(filedata > 50, axis = 1))


# now checking if all the values with respect to the axis = 0 or axis = 1 are greater than 50
print(np.all(filedata > 50, axis = 0)) # across column
print(np.all(filedata > 50, axis = 1)) # across rows

# greater than 50 and less than 100
print("\n\ngreater than 50 and less than 100")
print(((filedata > 50) & (filedata < 100))) # (filedata > 50 & filedata < 100) wont work

[[ 11. 178.  44.  41.  52.  46.  84.   5.  63.  98.  63.]
 [  3.   2.   5.   6.  89.  56.  22.  33.  54.  65.  89.]]
[False  True False False  True  True  True False  True  True  True]
[[ 11. 178.  44.  41.  52.  46.  84.   5.  63.  98.  63.]
 [  3.   2.   5.   6.  89.  56.  22.  33.  54.  65.  89.]]
[ True  True]
[False False False False  True False False False  True  True  True]
[False False]


greater than 50 and less than 100
[[False False False False  True False  True False  True  True  True]
 [False False False False  True  True False False  True  True  True]]


In [104]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [106]:
# slicing 11,12,16,17
print(a[2:4,0:2])

# slicing 2,8,14,20
a[1:]

[[11 12]
 [16 17]]
